use_frameworks!

target 'NetworkDetector_iOS_Example' do
  platform :ios, '12.0'
  
  pod 'NetworkDetector', :path => '../'
end

target 'NetworkDetector_macOS_Example' do
  platform :osx, '10.14'
  
  pod 'NetworkDetector', :path => '../'
end

target 'NetworkDetector_tvOS_Example' do
    platform :tvos, '12.0'
    
    pod 'NetworkDetector', :path => '../'
end

target 'NetworkDetector_Tests' do
    platform :ios, '12.0'
    inherit! :search_paths
    
    pod 'NetworkDetector', :path => '../'    
end
